[Cartas]
jocker = "tar_comodin.png"
ballon = "tar_globo.png"
cannon = "tar_canon.png"
ship = "tar_galeon.png"

[Sudamerica]
pos_x = 190 
pos_y = 210

[Sudamerica.Argentina]
continente = "Sudamerica"
file = "classic/argentina.png"
pos_x = 31
pos_y = 68
army_x = 0
army_y = 0

[Sudamerica.Brasil]
continente = "Sudamerica"
file = "classic/brasil.png"
pos_x = 30
pos_y = 8
army_x = 0
army_y = 0

[Sudamerica.Peru]
continente = "Sudamerica"
file = "classic/peru.png"
pos_x = 1
pos_y = 36
army_x = 0
army_y = 0

[Sudamerica.Colombia]
continente = "Sudamerica"
file = "classic/colombia.png"
pos_x = 0
pos_y = 0
army_x = 0
army_y = 0

[Sudamerica.Chile]
continente = "Sudamerica"
file = "classic/chile.png"
pos_x = 16
pos_y = 70
army_x = 0
army_y = 0

[Sudamerica.Uruguay]
continente = "Sudamerica"
file = "classic/uruguay.png"
pos_x = 51
pos_y = 54
army_x = 0
army_y = 10

[Oceania]
pos_x = 500
pos_y = 240

[Oceania.Sumatra]
continente = "Oceania"
file = "classic/sumatra.png"
pos_x = 29
pos_y = 20
army_x = 0
army_y = 0

[Oceania.Borneo]
continente = "Oceania"
file = "classic/borneo.png"
pos_x = 79
pos_y = 4
army_x = 0
army_y = 0

[Oceania.Java]
continente = "Oceania"
file = "classic/java.png"
pos_x = 116
pos_y = 4
army_x = 0
army_y = 0

[Oceania.Australia]
continente = "Oceania"
file = "classic/australia.png"
pos_x = 59
pos_y = 49
army_x = 0
army_y = 0

[Europa]
pos_x = 260
pos_y = 25

[Europa.Francia]
continente = "Europa"
file = "classic/francia.png"
pos_x = 111
pos_y = 105
army_x = 0
army_y = 10

[Europa.Espana]
continente = "Europa"
file = "classic/espania.png"
pos_x = 69
pos_y = 126
army_x = 0
army_y = 0

[Europa.Islandia]
continente = "Europa"
file = "classic/islandia.png"
pos_x = 52
pos_y = 44
army_x = 0
army_y = 0

[Europa.GranBretana]
continente = "Europa"
file = "classic/gran_bretania.png"
pos_x = 91
pos_y = 56
army_x = 0
army_y = 0

[Europa.Alemania]
continente = "Europa"
file = "classic/alemania.png"
pos_x = 135
pos_y = 92
army_x = 0
army_y = -5

[Europa.Italia]
continente = "Europa"
file = "classic/italia.png"
pos_x = 133
pos_y = 138
army_x = 0
army_y = -5

[Europa.Polonia]
continente = "Europa"
file = "classic/polonia.png"
pos_x = 148
pos_y = 87
army_x = 5
army_y = 0

[Europa.Rusia]
continente = "Europa"
file = "classic/rusia.png"
pos_x = 155
pos_y = 20
army_x = 0
army_y = 0

[Europa.Suecia]
continente = "Europa"
file = "classic/suecia.png"
pos_x = 115
pos_y = 2
army_x = 0
army_y = 0

[Africa]
pos_x = 340
pos_y = 240

[Africa.Sahara]
continente = "Africa"
file = "classic/sahara.png"
pos_x = 1
pos_y = 4
army_x = 0
army_y = 0

[Africa.Etiopia]
continente = "Africa"
file = "classic/etiopia.png"
pos_x = 65
pos_y = 29
army_x = 0
army_y = 0

[Africa.Egipto]
continente = "Africa"
file = "classic/egipto.png"
pos_x = 61
pos_y = 0
army_x = 0
army_y = 0

[Africa.Madagascar]
continente = "Africa"
file = "classic/madagascar.png"
pos_x = 149
pos_y = 39
army_x = 0
army_y = 0

[Africa.Zaire]
continente = "Africa"
file = "classic/zaire.png"
pos_x = 43
pos_y = 44
army_x = 0
army_y = 0

[Africa.Sudafrica]
continente = "Africa"
file = "classic/sudafrica.png"
pos_x = 95
pos_y = 62
army_x = 0
army_y = 0



[Norteamerica]
pos_x = 10
pos_y = 0


[Norteamerica.Canada]
continente = "Norteamerica"
file = "classic/canada.png"
pos_x = 83
pos_y = 4
army_x = 0
army_y = 0

[Norteamerica.Yukon]
continente = "Norteamerica"
file = "classic/yukon.png"
pos_x = 60
pos_y = 34
army_x = 0
army_y = 0

[Norteamerica.Alaska]
continente = "Norteamerica"
file = "classic/alaska.png"
pos_x = 23
pos_y = 69
army_x = 0
army_y = 0

[Norteamerica.Groenlandia]
continente = "Norteamerica"
file = "classic/groenlandia.png"
pos_x = 216
pos_y = 22
army_x = 0
army_y = 0

[Norteamerica.Oregon]
continente = "Norteamerica"
file = "classic/oregon.png"
pos_x = 26
pos_y = 110
army_x = 0
army_y = 0

[Norteamerica.California]
continente = "Norteamerica"
file = "classic/california.png"
pos_x = 71
pos_y = 153
army_x = -20
army_y = -20

[Norteamerica.Mexico]
continente = "Norteamerica"
file = "classic/mexico.png"
pos_x = 122
pos_y = 168
army_x = 0
army_y = 0

[Norteamerica.NuevaYork]
continente = "Norteamerica"
file = "classic/nuevayork.png"
pos_x = 117
pos_y = 96
army_x = -10
army_y = 10

[Norteamerica.Terranova]
continente = "Norteamerica"
file = "classic/terranova.png"
pos_x = 145
pos_y = 86
army_x = 0
army_y = 0

[Norteamerica.Labrador]
continente = "Norteamerica"
file = "classic/labrador.png"
pos_x = 177
pos_y = 59
army_x = 0
army_y = 0

[Asia]
pos_x = 320
pos_y = 15

[Asia.Arabia]
continente = "Asia"
file = "classic/arabia.png"
pos_x = 169
pos_y = 148
army_x = 0
army_y = 0

[Asia.Aral]
continente = "Asia"
file = "classic/aral.png"
pos_x = 129
pos_y = 19
army_x = 0
army_y = 0

[Asia.China]
continente = "Asia"
file = "classic/china.png"
pos_x = 205
pos_y = 16
army_x = 0
army_y = 20

[Asia.India]
continente = "Asia"
file = "classic/india.png"
pos_x = 198
pos_y = 128
army_x = 0
army_y = 0

[Asia.Iran]
continente = "Asia"
file = "classic/iran.png"
pos_x = 141
pos_y = 57
army_x = -11
army_y = 15

[Asia.Tartaria]
continente = "Asia"
file = "classic/tartaria.png"
pos_x = 141
pos_y = -1
army_x = 0
army_y = 0

[Asia.Taimiria]
continente = "Asia"
file = "classic/taimiria.png"
pos_x = 173
pos_y = 0
army_x = 0
army_y = 0

[Asia.Japon]
continente = "Asia"
file = "classic/japon.png"
pos_x = 277
pos_y = 33
army_x = 0
army_y = 0

[Asia.Kamchatka]
continente = "Asia"
file = "classic/kamchatka.png"
pos_x = 224
pos_y = -10
army_x = 0
army_y = 0

[Asia.Siberia]
continente = "Asia"
file = "classic/siberia.png"
pos_x = 158
pos_y = -2
army_x = 27
army_y = 5

[Asia.Mongolia]
continente = "Asia"
file = "classic/mongolia.png"
pos_x = 156
pos_y = 45
army_x = 22
army_y = -5

[Asia.Gobi]
continente = "Asia"
file = "classic/gobi.png"
pos_x = 164
pos_y = 67
army_x = 0
army_y = 0

[Asia.Malasia]
continente = "Asia"
file = "classic/malasia.png"
pos_x = 243
pos_y = 122
army_x = 0
army_y = 0

[Asia.Turquia]
continente = "Asia"
file = "classic/turquia.png"
pos_x = 132
pos_y = 124
army_x = -12
army_y = -5

[Asia.Israel]
continente = "Asia"
file = "classic/israel.png"
pos_x = 147
pos_y = 146
army_x = 0
army_y = 0
